### PR TITLE
Add canva.dev

### PR DESCRIPTION
**Pull request by vrslev**

### CODE REVIEW

**Comment by misha-tgshv** [comment]
Add file

**Comment by vrslev** [comment]
What exactly do you mean?

**Comment by vrslev** [comment]
Another file with custom domains?

**Comment by misha-tgshv** [comment]
All domains that are not in the antifilter list are added to the [custom.list](https://github.com/misha-tgshv/shadowrocket-configuration-file/blob/main/custom.list)

**Pull request closed without merging**
